In [ ]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [ ]:

# Reading the dataset
df = pd.read_csv('diabetes.csv')


In [ ]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
# Splitting the dataset into input and target variables
X = df.drop(['Outcome'], axis=1).values  # values takes only numerical values of the dataframe
y = df['Outcome'].values

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
# Creating the model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

Sequential() is a function that initializes a sequential model. A sequential model is a linear stack of layers, where you can add one layer at a time using the add() method.

Dense() is a layer type that is used for a fully connected layer in the neural network. It means that every neuron in the previous layer is connected to every neuron in the current layer.

Neural networks are composed of interconnected layers of artificial neurons, and each neuron has a certain number of units.

Each unit in a neural network layer represents a node or a neuron. The number of units in a layer determines the dimensionality or size of that layer. The units in the input layer correspond to the number of features or inputs in your data. For example, if you have an input layer with 10 units, it means you have 10 features or variables.

In subsequent layers, the number of units determines the number of artificial neurons in that layer. The units in these layers capture and learn various patterns, features, or representations from the input data. The higher the number of units, the more complex patterns the layer can learn.

By adjusting the number of units in different layers, you can control the capacity and complexity of the neural network. It's important to strike a balance between having enough units to capture important features without overfitting the model to the training data.


The first Dense() layer has 12 units and expects an input of shape (8,) because of input_dim=8. The activation function used in this layer is Rectified Linear Unit (ReLU), which is a popular activation function that introduces non-linearity to the neural network.

The second Dense() layer has 8 units and also uses ReLU as the activation function.

The final Dense() layer has 1 unit and uses sigmoid as the activation function. Sigmoid function returns a value between 0 and 1, which is suitable for binary classification problems where we want to predict the probability of an input belonging to a certain class.

So, in summary, this is a simple neural network model with 2 hidden layers having 12 and 8 neurons respectively, and an output layer with 1 neuron for binary classification. The model uses ReLU as the activation function for the hidden layers and sigmoid as the activation function for the output layer.



In [ ]:
# Compiling the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


After building the neural network architecture, the next step is to compile the model. The compile() method configures the model for training by specifying the loss function, optimizer, and evaluation metrics.

loss='binary_crossentropy' specifies the loss function to use during training. Binary cross-entropy is a commonly used loss function for binary classification problems, where we want to minimize the difference between the predicted probabilities and the true labels.

optimizer='adam' specifies the optimization algorithm to use during training. Adam is a popular optimization algorithm that uses adaptive learning rates and momentum to converge faster and more reliably.

metrics=['accuracy'] specifies the evaluation metric to use during training and testing. Accuracy is a metric that measures the fraction of correctly classified samples. It is a commonly used metric for classification problems.

So, in summary, this code compiles the neural network model with binary cross-entropy as the loss function, Adam as the optimization algorithm, and accuracy as the evaluation metric.







In [ ]:
# Training the model# Keep increasing the Epoch and batch size till loss and accuracy remain at stagnant levels
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 2.3693 - accuracy: 0.4583
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 0.9832 - accuracy: 0.4440
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7527 - accuracy: 0.6107
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6876 - accuracy: 0.6484
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6598 - accuracy: 0.6667
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6414 - accuracy: 0.6745
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6316 - accuracy: 0.6706
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6223 - accuracy: 0.6732
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6139 - accuracy: 0.6836
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6068 - accuracy: 0.6628
Epoch 11/

X represents the input data to the model, and y represents the corresponding target labels for the input data.

epochs=150 specifies the number of times the model will iterate over the entire training dataset during training. One epoch means that the model has gone through the entire training dataset once.

batch_size=10 specifies the number of samples that will be propagated through the network at once. The weights of the network will be updated based on the gradients calculated on these samples. This is known as stochastic gradient descent.

During training, the model will forward propagate the input data through the network, compute the loss using the specified loss function, and then backpropagate the error to update the weights of the network using the specified optimizer. This process continues for the specified number of epochs or until the model reaches convergence.

So, in summary, this code trains the compiled neural network model with the given input data X and target labels y for 150 epochs, with each epoch training the model on batches of 10 samples at a time.








In [ ]:
# Evaluating the model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))


24/24 [==============================] - 0s 1ms/step - loss: 0.4770 - accuracy: 0.7695
Accuracy: 76.95


model.evaluate(X, y) is a method that evaluates the trained model on the given test data and returns the loss value and evaluation metric value(s) specified during model compilation.

X represents the input data to the model, and y represents the corresponding target labels for the input data. The first output of the method (loss function) is ignored by assigning it to the dummy variable _, and the second output (accuracy)is assigned to the variable accuracy.

So, in summary, this code evaluates the trained neural network model on the given test data X and target labels y and returns the calculated loss value, which is ignored, and the accuracy metric value, which is stored in the accuracy variable.

In [ ]:
# Predict Outcome for New Pateint X_new with parameters
#Pregnancies	Glucose	BloodPressure	SkinThickness	Insulin	BMI	DiabetesPedigreeFunction	Age	
#8	183	64	0	0	23.3	0.672	32

X_new =[[8,	183	,64	,0,	0	,23.3	,0.672	,32]]

In [ ]:
X_new

[[8, 183, 64, 0, 0, 23.3, 0.672, 32]]

In [ ]:
y_pred = model.predict(X_new)


1/1 [==============================] - 0s 160ms/step


In [ ]:
y_pred

array([[0.93569064]], dtype=float32)

In [ ]:
import numpy as np  #This will convert the predicted probabilities to binary labels using a threshold of 0.5.
# The resulting y_pred_binary array will contain 1's and 0's indicating the predicted class label for each input instance.

threshold = 0.5
y_pred_binary = np.where(y_pred > threshold, 1, 0)


In [ ]:
y_pred_binary

array([[1]])